{"name": "Ошибка при попытке принять заказ без или с неверным id заказа", "status": "passed", "description": "Ошибка при попытке принять заказ без или с неверным id заказа.", "steps": [{"name": "Авторизация курьера.", "status": "passed", "parameters": [{"name": "account_data", "value": "{'firstName': 'TaEGinwjpa', 'login': 'gnjNZOnEQD', 'password': 'thKqyzrMQw'}"}], "start": 1733420192937, "stop": 1733420193002}, {"name": "Принятие заказа курьером.", "status": "passed", "parameters": [{"name": "order_id", "value": "0"}, {"name": "courier_id", "value": "429193"}], "start": 1733420193002, "stop": 1733420193105}], "parameters": [{"name": "order_id", "value": "0"}, {"name": "expected", "value": "(404, 'Заказа с таким id не существует')"}], "start": 1733420192936, "stop": 1733420193106, "uuid": "f0ecffba-164f-4e9b-b2f2-d2f1d024ae6a", "historyId": "417b180a8c11ac03cd923507d1810202", "testCaseId": "bfea77d0d0d5feb53437bd736cae6341", "fullName": "tests.orders.test_orders_accept.TestOrdersAccept#test_accept_order_no_or_wrong_order_id_error", "labels": [{"name": "parentSuite", "value": "tests.orders"}, {"name": "suite", "value": "test_orders_accept"}, {"name": "subSuite", "value": "TestOrdersAccept"}, {"name": "host", "value": "ZenBook"}, {"name": "thread", "value": "12392-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.test_orders_accept"}]}