{"name": "Ошибка при попытке принять заказ без или с неверным id заказа", "status": "passed", "description": "Ошибка при попытке принять заказ без или с неверным id заказа.", "steps": [{"name": "Авторизация курьера.", "status": "passed", "parameters": [{"name": "account_data", "value": "{'firstName': 'AmxBtqCjbd', 'login': 'NCZEEdCRSH', 'password': 'sHCEWZddTW'}"}], "start": 1733420325939, "stop": 1733420326004}, {"name": "Принятие заказа курьером.", "status": "passed", "parameters": [{"name": "order_id", "value": "''"}, {"name": "courier_id", "value": "429201"}], "start": 1733420326004, "stop": 1733420326081}], "parameters": [{"name": "order_id", "value": "''"}, {"name": "expected", "value": "(404, 'Not Found.')"}], "start": 1733420325939, "stop": 1733420326081, "uuid": "9d6ef783-e79e-4d3b-b7ec-a61317b7ecde", "historyId": "56c54dedcaa5c40fafa6db86d44bd784", "testCaseId": "bfea77d0d0d5feb53437bd736cae6341", "fullName": "tests.orders.test_orders_accept.TestOrdersAccept#test_accept_order_no_or_wrong_order_id_error", "labels": [{"name": "parentSuite", "value": "tests.orders"}, {"name": "suite", "value": "test_orders_accept"}, {"name": "subSuite", "value": "TestOrdersAccept"}, {"name": "host", "value": "ZenBook"}, {"name": "thread", "value": "14132-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.test_orders_accept"}]}