{"name": "Ошибка при попытке принять заказ без или с неверным id заказа", "status": "passed", "description": "Ошибка при попытке принять заказ без или с неверным id заказа.", "steps": [{"name": "Авторизация курьера.", "status": "passed", "parameters": [{"name": "account_data", "value": "{'firstName': 'GptyTGXxPZ', 'login': 'iLowMrqyhH', 'password': 'fyZLVwddfE'}"}], "start": 1733420193268, "stop": 1733420193332}, {"name": "Принятие заказа курьером.", "status": "passed", "parameters": [{"name": "order_id", "value": "''"}, {"name": "courier_id", "value": "429194"}], "start": 1733420193332, "stop": 1733420193396}], "parameters": [{"name": "order_id", "value": "''"}, {"name": "expected", "value": "(404, 'Not Found.')"}], "start": 1733420193267, "stop": 1733420193397, "uuid": "242df576-6fe2-42b2-9c2b-3bede78d5580", "historyId": "56c54dedcaa5c40fafa6db86d44bd784", "testCaseId": "bfea77d0d0d5feb53437bd736cae6341", "fullName": "tests.orders.test_orders_accept.TestOrdersAccept#test_accept_order_no_or_wrong_order_id_error", "labels": [{"name": "parentSuite", "value": "tests.orders"}, {"name": "suite", "value": "test_orders_accept"}, {"name": "subSuite", "value": "TestOrdersAccept"}, {"name": "host", "value": "ZenBook"}, {"name": "thread", "value": "12392-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.test_orders_accept"}]}